# Generated by Django 6.0.7 on 2026-07-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_skillrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Pccepted', 'accepted'), ('Pejected', 'rejected')], default='pending', max_length=20),
        ),
    ]
