# Generated by Django 6.0.7 on 2026-07-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0004_alter_skillrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
