# Generated by Django 6.0.7 on 2026-08-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='session',
        ),
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
