# Generated by Django 6.0.7 on 2026-08-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_course_host_remove_course_participant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video_url',
            field=models.URLField(help_text='Required YouTube tutorial URL.'),
        ),
    ]
