# Generated by Django 6.0.7 on 2026-07-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='experience',
            new_name='career_level',
        ),
    ]
